### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by TankHung** [2018-summer-DL-training-program/Lab-2-Image-Captioning#8]
請問各位, 是否有遇過我title放的那個問題?

我是照著mail的安裝流程走到
Preprocessing那一步, 但是卻遇到如下的問題
python3 build_vocab.py 

Traceback (most recent call last):
  File "build_vocab.py", line 5, in <module>
    from pycocotools.coco import COCO
  File "/proj/gpu_mtk02387/.local/lib/python3.5/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/proj/gpu_mtk02387/.local/lib/python3.5/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: /proj/gpu_mtk02387/.local/lib/python3.5/site-packages/pycocotools/_mask.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

  我去網路上查過, 似乎是FPE flag是否enable導致的python套件不相容的問題,
  但是重複uninstall/install cython, pycocotools
  也還是無法解決,

  請各位幫忙提供想法, 多謝~~

**Comment by pablosun** [comment]
Hi @TankHung ,

我這邊不會有`PyFPE_jbuf`的問題，我把我的 `~/.local/lib/python3.5/site-packages/` 打包放上來，也許可以跟你的比對一下，看是不是檔案真的有不一樣。

如果檔案一樣，但是結果不同，那就比較可能是執行環境（也許跟 shell RC 的 Python 設定有關？）

[site-packages.zip](https://github.com/2018-summer-DL-training-program/Lab-2-Image-Captioning/files/2301081/site-packages.zip)

**Comment by TankHung** [comment]
@pablosun 多謝協助~~

Vanessa已經提供以下解法, 我實測過是有效的,
謝謝~~

==============================================
請記得在pip3 install 之前要module load Python3/3.5.2_gpu_torch

如果出現這錯誤訊息
.local/lib/python3.5/site-packages/pycocotools/_mask.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
請依照以下步驟重新操作
1. module load Python3/3.5.2_gpu_torch
2. rm -rf ~/.cache/pip/
3. pip3 install cython --user --ignore-installed
4. pip3 install pycocotools --user --ignore-installed
